### ISSUE TITLE
Feature Request: Get Liked Posts

### ISSUE THREAD

**Issue by chris-79** [snarfed/instagram-atom#2]
First and foremost: **_AWESOME_** app! Thanks _so much_ for doing this!

Not sure you even take FRs, but might there be a way of adding a parameter to get different parts of our profiles like Liked Posts? Trying to find a good way of saving what I've liked outside of IG

– Chris :)

**Comment by snarfed** [comment]
thanks for the kind words!

instagram doesn't actually expose likes anywhere i can get at them easily, sadly, in either the API or a scrapeable web page, so they're not really doable right now.

**Comment by chris-79** [comment]
Yeah, I guess it's not an easy add. Somehow Zapier.com has figured it out, but it's too overpriced for what I want to do with it

Also, maybe they have a special deal with IG
¯\_(ツ)_/¯

Thanks for entertaining the idea, though!
