### ISSUE TITLE
feature request: move images to atom enclosures

### ISSUE THREAD

**Issue by aaronpk** [snarfed/instagram-atom#3]
I'd love to see the instagram photos added as atom enclosures rather than being embedded in the HTML. When I run an instagram-atom feed through XRay to convert it to the jf2 format used by my new reader, right now the images just appear in the embedded HTML. Ideally they'd show up in XRay's `photo` property, but I can only do that if they're marked as atom enclosures. Maybe this could be a query string parameter to change the behavior since I know some feed readers won't support that attachment very well.

**Comment by snarfed** [comment]
sure! worth considering. looks like we also investigated this somewhat thoroughly a bit ago in https://github.com/snarfed/granary/issues/113.

**Comment by snarfed** [comment]
interesting, just found another alternative, at least for single photo/video posts: they could be the top-level content, e.g. `<content type="image/png" src="/mypng1.png" />`. full example: https://www.ibm.com/developerworks/library/x-atom10/index.html#N10119

no idea how reader support for this is. probably even worse than for image enclosures...which is already the main reason i'm reluctant here. :/

**Comment by Nick-Shannon** [comment]
Hi, the instagram-atom is great. 
However, my feed is broken :(. 

FYI, I added the instagram-atom feed to Feed Burner.  I've also use an IFTTT applet to post my instagram feed toa private twitter account - so I can have my Instagram in my Twitter :). 
The IFTTT applet requires: {{EntryImageUrl}} 

Has there been a recent change to the instagram-atom tool?

**Comment by snarfed** [comment]
thanks for reporting, @Nick-Shannon! looks like there was a minor Atom validation error. i've fixed it and pushed the update. let me know if your feed is happy now! or if not, please post the specific error you're seeing and any other details.

**Comment by Nick-Shannon** [comment]
Thanks @snarfed.  Feed is back to normal! Thanks for the rapid fix.

**Comment by snarfed** [comment]
done in snarfed/granary@92341ea9c9e5b447e0bbd4be71ff371530942d1f. feel free to try @aaronpk!
