### ISSUE TITLE
Instagram-atom feed is empty.

### ISSUE THREAD

**Issue by Nick-Shannon** [snarfed/instagram-atom#4]
Hi - I regenerated my feed by grabbing a new sessionID, but my feed is still empty.  
Thanks for creating this service :).

**Comment by snarfed** [comment]
hey nick, sorry for the trouble, and thanks for the nudge! looks like IG changed their logged in home page markup. i'll investigate soon.

**Comment by Nick-Shannon** [comment]
Yay.  Feed is working again. Thank you!

Looks great in my Today View :) 

<img src="https://nickspxts.files.wordpress.com/2018/10/widget.jpg">

**Comment by snarfed** [comment]
hah, funny. i didn't actually do anything. 🤷‍♀️

**Comment by Nick-Shannon** [comment]
The best kind of problems are the ones that resolve themselves :)
