### ISSUE TITLE
feed is blank 

### ISSUE THREAD

**Issue by Nick-Shannon** [snarfed/instagram-atom#9]
I read somewhere that Instagram is throttling requests based from tools that use SessionsIDs?  

Shame if this is the case :(

**Comment by snarfed** [comment]
Sorry for the trouble! It's probably not `sessionid` specifically, since your browser uses it too, but sadly yes, Instagram does detect and throttle automated usage like instagram-atom. It's an arms race that they have far more resources for than me, unfortunately. I'll add a warning to the page.

**Comment by Nick-Shannon** [comment]
Thanks for the info.  I've been using instagram-atom for a while now — and it's been great! 
Guess it was only a matter of time before Instagram took notice. 

Thank you for making this tool.  You need tip jar :).
